
select * from emp;

SELECT B.*FROM(SELECT ROWNUM AS RNUM, A.* FROM(SELECT * FROM EMP) A) B WHERE RNUM BETWEEN 2 AND 4;

SELECT B.*FROM(SELECT ROWNUM AS RNUM, A.* FROM(SELECT * FROM EMP) A) B WHERE RNUM BETWEEN 11 AND 14;

SELECT B.*FROM(SELECT ROWNUM AS RNUM, A.* FROM(SELECT * FROM EMP) A) B WHERE RNUM BETWEEN 1 AND 14 AND ENAME LIKE '%MI%';


SELECT COUNT(*) FROM EMP WHERE ENAME LIKE '%M%';
SELECT COUNT(*) FROM EMP WHERE ENAME LIKE #{searchKeyword}







